name: pr-merged

on:
  push:
    branches: [ "main" ]

jobs:
  archive-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Setup
      uses: ./.github/actions/setup-environment
    - name: Verify KSP version
      run: ci/verify-ksp-version.sh
    - name: Compile a release build
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
      run: ci/nightly-build.sh
    - name: Archive the APK
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: apk
        path: secrets/mozilla-social-nightly.apk
        if-no-files-found: error